#!/usr/bin/env bash
# @description backup to restic repository
# @import console/die
# @import lang/required
# @import github.com/escapace/stack-tools restic/restic

main () {
    strict  true
    verbose true

    _ required "${B2_ACCOUNT_ID}"  || _ die "B2_ACCOUNT_ID environment variable not set"
    _ required "${B2_ACCOUNT_KEY}" || _ die "B2_ACCOUNT_KEY environment variable not set"
    _ required "${B2_BUCKET_NAME}" || _ die "B2_BUCKET_NAME environment variable not set"

    _ restic backup \
        --exclude-file="${MANAGE_REPOSITORY}/scripts/restic/exclude.txt" \
        -o b2.connections=50 \
        -r b2:"${B2_BUCKET_NAME}":/ "${HOME}/devel"
}
