#!/usr/bin/env sh
# shellcheck disable=SC1090

export FZF_DEFAULT_OPTS='--color bw'

if [[ -d "$HOME/dotfiles/vendor/fzf/bin" ]]
then
    export PATH="$PATH:$HOME/dotfiles/vendor/fzf/bin"
fi

[[ $- =~ i ]] && source "$HOME/dotfiles/vendor/fzf/shell/completion.zsh" 2> /dev/null
source "$HOME/dotfiles/vendor/fzf/shell/key-bindings.zsh"
