#!/usr/bin/env sh

[ -d "$HOME/.vim-dist/bin/" ] && export PATH="$HOME/.vim-dist/bin:$PATH"
[ -d "$HOME/.neovim-dist/bin/" ] && export PATH="$HOME/.neovim-dist/bin:$PATH"

if command -v nvim > /dev/null 2>&1
then
    alias vi='nvim'
    alias vim='nvim'
    export EDITOR='nvim'
    export VISUAL='nvim'
else
    alias vi='vim'
    export EDITOR='vim'
    export VISUAL='vim'
fi

bindkey -M vicmd "v" edit-command-line
