# Enable manage repository scripts
enable:
  - help
  - trust-escapace

# Default script
default: help
env:
  # https://github.com/dandavison/delta
  DELTA_VERSION: 0.18.0
  # https://github.com/sharkdp/fd
  FD_VERSION: 10.2.0
  # https://github.com/junegunn/fzf
  FZF_VERSION: 0.53.0
  # https://github.com/antonmedv/fx
  FX_VERSION: 35.0.0
  # https://github.com/grafana/k6
  K6_VERSION: 0.53.0
  # https://github.com/restic/restic
  RESTIC_VERSION: 0.17.0
  # https://github.com/caarlos0/svu
  SVU_VERSION: 2.1.1
  # https://github.com/antonmedv/walk/
  WALK_VERSION: 1.10.0
  # https://github.com/ajeetdsouza/zoxide
  ZOXIDE_VERSION: 0.9.4
