#!/usr/bin/env bash
# @import console/die
# @import console/error
# @import console/die
# @import console/info
# @import lang/exists
# @import restic/AlexanderNeumannKey

downloadRestic ()
{
    verbose true
    strict true

    exists gpg || die "Cannot find 'gpg' in path."
    exists curl || die "Cannot find 'gpg' in path."
    exists bzip2 || die "Cannot find 'bzip2' in path."

    {
        AlexanderNeumannKey | gpg --import &> /dev/null
    } || die "Cannot import Alexander Neumann (https://github.com/fd0) GPG key"

    [ -z "${RESTIC_BINARY}" ] && die "'RESTIC_BINARY' is not defined"
    [ -z "${RESTIC_SHA256SUMS}" ] && die "'RESTIC_SHA256SUMS' is not defined"
    [ -z "${RESTIC_SHA256SUMS_SIGNATURE}" ] && die "'RESTIC_SHA256SUMS_SIGNATURE' is not defined"

    [ -z "${RESTIC_DIRECTORY}" ] && RESTIC_DIRECTORY="${MANAGE_REPOSITORY}/vendor/restic"

    if [ ! -f "${RESTIC_DIRECTORY}/restic" ]
    then
        mkdir -p "${RESTIC_DIRECTORY}"
        curl -0 -S -L --progress-bar "${RESTIC_BINARY}" -o "${RESTIC_DIRECTORY}/${RESTIC_BINARY##*/}"
        curl -0 -s -S -L "${RESTIC_SHA256SUMS}" -o "${RESTIC_DIRECTORY}/${RESTIC_SHA256SUMS##*/}"
        curl -0 -s -S -L "${RESTIC_SHA256SUMS_SIGNATURE}" -o "${RESTIC_DIRECTORY}/${RESTIC_SHA256SUMS_SIGNATURE##*/}"

        gpg --verify "${RESTIC_DIRECTORY}/${RESTIC_SHA256SUMS_SIGNATURE##*/}" \
            "${RESTIC_DIRECTORY}/${RESTIC_SHA256SUMS##*/}"

        local SHA256SUM
        SHA256SUM="$(grep "${RESTIC_BINARY##*/}" "${RESTIC_DIRECTORY}/${RESTIC_SHA256SUMS##*/}")"
        echo "${SHA256SUM}" > "${RESTIC_DIRECTORY}/${RESTIC_SHA256SUMS##*/}"

        (
            cd "${RESTIC_DIRECTORY}" || die
            sha256sum --status -c "${RESTIC_DIRECTORY}/${RESTIC_SHA256SUMS##*/}"
        )

        bzip2 -cd "${RESTIC_DIRECTORY}/${RESTIC_BINARY##*/}" > "${RESTIC_DIRECTORY}/restic"
        chmod +x "${RESTIC_DIRECTORY}/restic"

        rm -f "${RESTIC_DIRECTORY}/${RESTIC_BINARY##*/}" \
            "${RESTIC_DIRECTORY}/${RESTIC_SHA256SUMS##*/}" \
            "${RESTIC_DIRECTORY}/${RESTIC_SHA256SUMS_SIGNATURE##*/}"
    fi
}
