#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

fpath=("$HOME/dotfiles/zsh/internal" "${fpath[@]}")

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

umask 0027
export TERM="xterm-256color"

for file in $HOME/dotfiles/zsh/source/*; do
    if [[ -f "${file}" ]]
    then
        source "${file}"
    fi
done

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/nomad nomad
