#!/usr/bin/env bash
# @description restore ~/desktop from backblaze
# @import console/die
# @import console/info
# @import lang/exists

main () {
    strict  true
    verbose true

    [[ ! -d "${HOME}/desktop" ]] ||
    _ die "Desktop folder exists"

    # [[ ! -d "${HOME}/backup" ]] ||
    # _ die "Backup folder exists"

    _ exists "${MANAGE_REPOSITORY}/vendor/restic/restic" ||
        _ die "Download restic first"

    _ exists "${MANAGE_REPOSITORY}/vendor/rclone/rclone" ||
        _ die "Download rclone first"

    "${MANAGE_REPOSITORY}/vendor/rclone/rclone" sync backblaze:french-desktop "${HOME}/backup"

    mkdir "${HOME}/backup/tmp"   || true
    mkdir "${HOME}/backup/locks" || true

    "${MANAGE_REPOSITORY}/vendor/restic/restic" -r "${HOME}/backup" restore latest --target "${HOME}"

    _ info "Done."
}
