#!/usr/bin/env bash
#
# @description backup ~/desktop to backblaze
# @import console/die
# @import console/info
# @import lang/exists

main () {
    strict  true
    verbose true

    [[ -d "${HOME}/desktop" ]] ||
    _ die "Nothing to backup"

    [[ -d "${HOME}/backup" ]] ||
    _ die "Create restic repository first"

    _ exists "${MANAGE_REPOSITORY}/vendor/restic/restic" ||
        _ die "Download restic first"

    _ exists "${MANAGE_REPOSITORY}/vendor/rclone/rclone" ||
        _ die "Download rclone first"

    "${MANAGE_REPOSITORY}/vendor/restic/restic" backup -r "${HOME}/backup" "${HOME}/desktop"

    "${MANAGE_REPOSITORY}/vendor/rclone/rclone" sync "${HOME}/backup" backblaze:french-desktop

    _ info "Done."
}
