#!/usr/bin/env bash
#
# @import console/die
# @import console/info
# @import lang/required
# @description backup ~/.sensitive to a flash drive

cleanuptmp () {
    local dir
    for dir in "${temporary[@]}"
    do
        [ -d "$dir" ] && rm -rf "$dir"
    done
}

cleanup ()
{
    [ -d "$1" ] && temporary+=("$1")
}

tempdir ()
{
    local tempdir

    tempdir="$(dirname "$(mktemp -u)")/dotfiles-$1"

    [[ -d "${tempdir}" ]] && rm -rf "${tempdir}"

    mkdir -p "${tempdir}"

    if [[ ! -d "${tempdir}" ]]
    then
        _ die "Could not create temporary directory."
    fi

    cleanup "${tempdir}" || true

    echo "${tempdir}"
}

getdev () {
    _ required "$1" || return 1
    basename "$(readlink -f "/dev/disk/by-partlabel/$1")"
    # sudo lsblk -r -o name,label |
    # awk '(index($2, "'"$1"'") != 0) {print $1}' 
}

main () {
    strict  true
    verbose true

    [[ -d "${HOME}/.sensitive" ]] ||
    _ die "Nothing to backup."

    temporary=()
    local label="dotfiles_backup"

    device="$(getdev "${label}")"

    _ required "${device}" ||
    _ die "No backup device found."

    [[ -b "/dev/${device}" ]] ||
    _ die "No backup device found."

    sudo cryptsetup isLuks "/dev/${device}" ||
    _ die "'${device}' is not a LUKS device."

    if [[ -b "/dev/mapper/${device}" ]]
    then
        sudo cryptsetup close "${device}" || true
    fi

    sudo cryptsetup open "/dev/${device}" "${device}" 

    _ info "Device '${device}' opened."

    mountpoint="$(tempdir "${device}")"
    sudo umount -f "/dev/mapper/${device}" > /dev/null 2>&1  || true
    sudo mount "/dev/mapper/${device}" "${mountpoint}"
    sudo chown "${USER}" "${mountpoint}"

    if [[ -d "${mountpoint}/$(date +"%Y-%m-%d")" ]]
    then
        #shellcheck disable=SC2115
        rm -rf "${mountpoint}/$(date +"%Y-%m-%d")"
    fi

    cp -rf "${HOME}/.sensitive" "${mountpoint}/$(date +"%Y-%m-%d")"
    _ info "Done."
}

onExit () {
    sleep 2
    _ info "Unmounting filesystems."
    sudo umount -f "/dev/mapper/${device}" > /dev/null 2>&1  || true

    sudo cryptsetup close "${device}" || true
    _ info "Device '${device}' closed."

    _ info "Removing temporary files and directories."
    cleanuptmp
}
