#! /bin/sh

bspc monitor -d                             1 2 3 4 5 6 7 8 9

bspc config border_width                    0
bspc config window_gap                      12

bspc config split_ratio                     0.52
bspc config normal_frame_opacity            0.1
bspc config focused_frame_opacity           0.2
bspc config borderless_monocle              false
bspc config gapless_monocle                 false
bspc config focus_by_distance               true
bspc config focus_follows_pointer           false
bspc config auto_alternate                  true
bspc config auto_cancel                     true
bspc config apply_floating_atom             true
bspc config history_aware_focus             true
bspc config normal_border_color             "#1d2021"
bspc config focused_border_color            "#282828"
bspc config active_border_color             "#817267"
bspc config presel_border_color             "#9a875f"
bspc config urgent_border_color             "#9f7155"
bspc config focused_locked_border_color     "#9a875f"
bspc config top_padding 28
bspc config bottom_padding 2
bspc config focus_follows_pointer true

