#!/usr/bin/env bash
# @description install dotfiles (minimal)
# @dependency zsh
# @dependency git
# @import dotfiles/runcoms

main () {
    strict  true
    verbose true

    if [ -d "$HOME/dotfiles" ] || [ -L "$HOME/dotfiles" ]; then
        local path
        path="$HOME/dotfiles"
        local OPWD=$PWD ; cd "${path}" || exit
        # git pull --recurse-submodules
        _ runcoms install "${HOME}"/dotfiles/zsh/runcoms
        cd "${HOME}/dotfiles/vendor/fzf" && "${HOME}/dotfiles/vendor/fzf/install" --bin
        cd "${OPWD}" || exit
    fi
}

