#!/usr/bin/env bash
# @description install k6
# @dependency curl
# @dependency tar
# @import console/error
# @import console/die

main() {
  strict true
  verbose true

  local version="${K6_VERSION}"
  local directory="${MANAGE_REPOSITORY}/vendor/k6"

  local os
  local extension
  local architecture

  architecture="$(uname -m)"
  os="$(uname)"

  case "${os}" in
  Linux)
    os="linux"
    extension="tar.gz"
    ;;
  Darwin)
    os="macos"
    extension="zip"
    ;;
  *)
    _ die "Unknown OS type"
    ;;
  esac

  case "${architecture}" in
  x86_64)
    architecture="amd64"
    ;;
  aarch64 | arm64)
    architecture="arm64"
    ;;
  *)
    _ die "Unknown architecture: $(uname -m)"
    return 1
    ;;
  esac

  local prefix="https://github.com/grafana/k6/releases/download/v${version}"
  local archive="${prefix}/k6-v${version}-${os}-${architecture}.${extension}"
  local checksums="${prefix}/k6-v${version}-checksums.txt"

  if [[ ! -f "${directory}/k6" ]]; then
    mkdir -p "${directory}"

    curl -0 -S -L --progress-bar "${archive}" -o "${directory}/${archive##*/}"
    curl -0 -s -S -L "${checksums}" -o "${directory}/checksums.txt"

    (
      cd "${directory}" || _ die

      if command -v "sha256sum" &>/dev/null; then
        sha256sum --ignore-missing --status -c "${directory}/checksums.txt"
      elif command -v "shasum" &>/dev/null; then
        shasum -a 256 --ignore-missing --status -c "${directory}/checksums.txt"
      else
        _ die "No sha256sum or shasum in \$PATH."
      fi

      rm -f "${directory}/checksums.txt"
    )

    (
      cd "${directory}" || _ die

      if [[ "${extension}" == "tar.gz" ]]; then
        tar -zxvf "${directory}/${archive##*/}" k6
      elif [[ "${extension}" == "zip" ]]; then
        unzip -oqq "${directory}/${archive##*/}" -d "${directory}"
      fi

      rm -f "${directory}/${archive##*/}"

      mv "${directory}"/k6-*/k6 "${directory}/k6"
      rmdir "${directory}"/k6-*

      chmod +x k6

      if [[ ! -f "${HOME}/.dotfiles/bin/k6" ]]; then
        ln -s "${directory}/k6" "${HOME}/.dotfiles/bin/k6"
      fi

      rm -f "${directory}/${archive##*/}"
    )
  fi
}
