#!/usr/bin/env bash
# @description install sops
# @dependency curl
# @dependency tar
# @dependency cosign
# @import console/error
# @import console/die

main() {
  strict true
  verbose true

  local version="${SOPS_VERSION}"

  local os

  os="$(uname)"

  case "${os}" in
  Linux)
    os="linux"
    ;;
  Darwin)
    os="darwin"
    ;;
  *)
    _ die "Unknown OS type"
    ;;
  esac

  local architecture

  architecture="$(uname -m)"

  case "${architecture}" in
  x86_64)
    architecture="amd64"
    ;;
  aarch64 | arm64)
    architecture="arm64"
    ;;
  *)
    _ die "Unknown architecture: $(uname -m)"
    return 1
    ;;
  esac

  local directory="${MANAGE_REPOSITORY}/vendor/sops"

  local prefix="https://github.com/getsops/sops/releases/download/v${version}"
  local binary="${prefix}/sops-v${version}.${os}.${architecture}"
  local checksums="${prefix}/sops-v${version}.checksums.txt"
  local certificate="${prefix}/sops-v${version}.checksums.pem"
  local signature="${prefix}/sops-v${version}.checksums.sig"

  if [[ ! -f "${directory}/sops" ]]; then
    mkdir -p "${directory}"

    curl -0 -s -S -L "${checksums}" -o "${directory}/checksums.txt"
    curl -0 -s -S -L "${certificate}" -o "${directory}/certificate.pem"
    curl -0 -s -S -L "${signature}" -o "${directory}/certificate.sig"

    cosign verify-blob "${directory}/checksums.txt" \
      --certificate "${directory}/certificate.pem" \
      --signature "${directory}/certificate.sig" \
      --certificate-identity-regexp=https://github.com/getsops \
      --certificate-oidc-issuer=https://token.actions.githubusercontent.com

    curl -0 -S -L --progress-bar "${binary}" -o "${directory}/${binary##*/}"

    (
      cd "${directory}" || _ die

      if command -v "sha256sum" &>/dev/null; then
        sha256sum --ignore-missing --status -c "${directory}/checksums.txt"
      elif command -v "shasum" &>/dev/null; then
        shasum -a 256 --ignore-missing --status -c "${directory}/checksums.txt"
      else
        _ die "No sha256sum or shasum in \$PATH."
      fi

      rm -f "${directory}/checksums.txt"
    )

    (
      cd "${directory}" || _ die
      mv "${directory}/${binary##*/}" sops
      chmod +x sops

      if [[ ! -f "${HOME}/.dotfiles/bin/sops" ]]; then
        ln -s "${directory}/sops" "${HOME}/.dotfiles/bin/sops"
      fi

      rm -f "${directory}/checksums.txt" \
        "${directory}/certificate.pem" \
        "${directory}/certificate.sig"
    )
  fi
}
