#!/usr/bin/env bash
# @description install difft
# @dependency curl
# @dependency tar
# @import console/error
# @import console/die

main() {
  strict true
  verbose true

  local version="${DIFFT_VERSION}"

  local os

  os="$(uname)"

  case "${os}" in
  Linux)
    os="unknown-linux-gnu"
    ;;
  Darwin)
    os="apple-darwin"
    ;;
  *)
    _ die "Unknown OS type"
    ;;
  esac

  local architecture

  architecture="$(uname -m)"

  case "${architecture}" in
  x86_64)
    architecture="x86_64"
    ;;
  aarch64 | arm64)
    architecture="aarch64"
    ;;
  *)
    _ die "Unknown architecture: $(uname -m)"
    return 1
    ;;
  esac

  #

  local directory="${MANAGE_REPOSITORY}/vendor/difft"

  local prefix="https://github.com/Wilfred/difftastic/releases/download/${version}"
  local binary="${prefix}/difft-${architecture}-${os}.tar.gz"

  if [[ ! -f "${directory}/difft" ]]; then
    mkdir -p "${directory}"

    curl -0 -S -L --progress-bar "${binary}" -o "${directory}/${binary##*/}"

    (
      cd "${directory}" || _ die
      tar -zxvf "${directory}/${binary##*/}" "difft"
      chmod +x difft

      if [[ ! -f "${HOME}/.dotfiles/bin/difft" ]]; then
        ln -s "${directory}/difft" "${HOME}/.dotfiles/bin/difft"
      fi

      rm -f "${directory}/${binary##*/}"
    )
  fi
}
