#!/usr/bin/env bash
# @description install svu
# @dependency curl
# @dependency tar
# @import console/error
# @import console/die

main() {
  strict true
  verbose true

  local version="${SVU_VERSION}"

  local os

  os="$(uname)"

  case "${os}" in
    Linux)
      os="linux"
      ;;
    Darwin)
      os="darwin"
      ;;
    *)
      _ die "Unknown OS type"
      ;;
  esac

  local architecture

  if [[ "${os}" == "darwin" ]]; then
    architecture="all"
  else
    architecture="$(uname -m)"

    case "${architecture}" in
      x86_64)
        architecture="amd64"
        ;;
      aarch64)
        architecture="arm64"
        ;;
      *)
        _ die "Unknown architecture: $(uname -m)"
        return 1
        ;;
    esac
  fi

  local directory="${MANAGE_REPOSITORY}/vendor/svu"

  local prefix="https://github.com/caarlos0/svu/releases/download/v${version}"
  local binary="${prefix}/svu_${version}_${os}_${architecture}.tar.gz"
  local checksums="${prefix}/checksums.txt"

  if [[ ! -f "${directory}/svu" ]]; then
    mkdir -p "${directory}"

    curl -0 -S -L --progress-bar "${binary}" -o "${directory}/${binary##*/}"
    curl -0 -s -S -L "${checksums}" -o "${directory}/checksums.txt"

    (
      cd "${directory}" || _ die

      if command -v "sha256sum" &> /dev/null; then
        sha256sum --ignore-missing --status -c "${directory}/checksums.txt"
      elif command -v "shasum" &> /dev/null; then
        shasum -a 256 --ignore-missing --status -c "${directory}/checksums.txt"
      else
        _ die "No sha256sum or shasum in \$PATH."
      fi

      rm -f "${directory}/checksums.txt"
    )

    (
      cd "${directory}" || _ die
      tar -zxvf "${directory}/${binary##*/}" svu
      chmod +x svu

      if [[ ! -f "${HOME}/.dotfiles/bin/svu" ]]; then
        ln -s "${directory}/svu" "${HOME}/.dotfiles/bin/svu"
      fi

      rm -f "${directory}/${binary##*/}"
    )
  fi
}
