#!/usr/bin/env bash
# @description install fd
# @dependency curl
# @dependency tar
# @import console/error
# @import console/die

main() {
  strict true
  verbose true

  local version="${FD_VERSION}"

  local os

  os="$(uname)"

  case "${os}" in
  Linux)
    os="unknown-linux"
    ;;
  Darwin)
    os="apple-darwin"
    ;;
  *)
    _ die "Unknown OS type"
    ;;
  esac

  local architecture

  if [[ "${os}" == "darwin" ]]; then
    architecture="all"
  else
    architecture="$(uname -m)"

    case "${architecture}" in
    x86_64)
      architecture="x86_64"
      ;;
    aarch64 | arm64)
      architecture="aarch64"
      ;;
    *)
      _ die "Unknown architecture: $(uname -m)"
      return 1
      ;;
    esac
  fi

  local directory="${MANAGE_REPOSITORY}/vendor/fd"
  local prefix="https://github.com/sharkdp/fd/releases/download/v${version}"
  local binary
  local name

  if [[ "${os}" == "apple-darwin" ]]; then
    name="fd-v${version}-${architecture}-${os}"
    binary="${prefix}/${name}.tar.gz"
  else
    name="fd-v${version}-${architecture}-${os}-gnu"
    binary="${prefix}/${name}.tar.gz"
  fi

  if [[ ! -f "${directory}/fd" ]]; then
    mkdir -p "${directory}"

    curl -0 -S -L --progress-bar "${binary}" -o "${directory}/${binary##*/}"

    (
      cd "${directory}" || _ die
      tar --strip-components 1 -zxvf "${directory}/${binary##*/}" "${name}/fd"
      chmod +x fd

      if [[ ! -f "${HOME}/.dotfiles/bin/fd" ]]; then
        ln -s "${directory}/fd" "${HOME}/.dotfiles/bin/fd"
      fi

      rm -f "${directory}/${binary##*/}"
    )
  fi
}
