#!/usr/bin/env bash
# @description install walk
# @dependency curl
# @dependency tar
# @import console/error
# @import console/die

main() {
  strict true
  verbose true

  local version="${WALK_VERSION}"

  local os

  os="$(uname)"

  case "${os}" in
  Linux)
    os="linux"
    ;;
  Darwin)
    os="darwin"
    ;;
  *)
    _ die "Unknown OS type"
    ;;
  esac

  local architecture

  architecture="$(uname -m)"

  case "${architecture}" in
  x86_64)
    architecture="amd64"
    ;;
  aarch64 | arm64)
    architecture="arm64"
    ;;
  *)
    _ die "Unknown architecture: $(uname -m)"
    return 1
    ;;
  esac

  local directory="${MANAGE_REPOSITORY}/vendor/walk"

  local prefix="https://github.com/antonmedv/walk/releases/download/v${version}"
  local binary="${prefix}/walk_${os}_${architecture}"

  if [[ ! -f "${directory}/walk" ]]; then
    mkdir -p "${directory}"

    curl -0 -S -L --progress-bar "${binary}" -o "${directory}/walk"
    chmod +x "${directory}/walk"
    ln -s "${directory}/walk" "${HOME}/.dotfiles/bin/walk"
  fi
}
