#!/usr/bin/env bash
# @description install dotfiles
# @dependency fish
# @dependency git
# @import dotfiles/runcoms
# @import manage/manage
# @import console/warn

main() {
  strict true
  verbose true

  # _ manage trust-escapace

  if [ -d "$HOME/.dotfiles" ] || [ -L "$HOME/.dotfiles" ]; then
    cd "$HOME/.dotfiles" || exit 1

    _ manage install-fzf
    _ manage install-svu
    _ manage install-fd
    _ manage install-delta
    _ manage install-zoxide
    _ manage install-walk
    _ manage install-fx

    if [[ ! -L "${HOME}/.config/fish" ]]; then
      _ warn "Deleting ${HOME}/.config/fish"

      rm -rf "${HOME}/.config/fish"
    fi

    _ runcoms install "${HOME}"/.dotfiles/runcoms
  fi
}
