#!/usr/bin/env bash
# @description install yazi
# @dependency curl
# @dependency tar
# @import console/error
# @import console/die

main() {
  strict true
  verbose true

  local version="${YAZI_VERSION}"
  local directory="${MANAGE_REPOSITORY}/vendor/yazi"

  local os
  local architecture

  architecture="$(uname -m)"
  os="$(uname)"

  case "${os}" in
  Linux)
    os="unknown-linux-gnu"
    ;;
  Darwin)
    os="apple-darwin"
    ;;
  *)
    _ die "Unknown OS type"
    ;;
  esac

  case "${architecture}" in
  x86_64)
    architecture="x86_64"
    ;;
  aarch64 | arm64)
    architecture="aarch64"
    ;;
  *)
    _ die "Unknown architecture: $(uname -m)"
    return 1
    ;;
  esac

  local prefix="https://github.com/sxyazi/yazi/releases/download/v${version}"
  local archive="${prefix}/yazi-${architecture}-${os}.zip"

  if [[ ! -f "${directory}/yazi" ]]; then
    mkdir -p "${directory}"

    curl -0 -S -L --progress-bar "${archive}" -o "${directory}/${archive##*/}"

    (
      cd "${directory}" || _ die

      unzip -oqq "${directory}/${archive##*/}" -d "${directory}"

      mv "${directory}"/yazi-*/yazi "${directory}/yazi"

      chmod +x yazi

      if [[ ! -f "${HOME}/.dotfiles/bin/yazi" ]]; then
        ln -s "${directory}/yazi" "${HOME}/.dotfiles/bin/yazi"
      fi

      rm -rf "${directory}/${archive##*/}"
    )
  fi
}
