#!/usr/bin/env bash
# @description install fx
# @dependency curl
# @dependency tar
# @import console/error
# @import console/die

main() {
  strict true
  verbose true

  local version="${FX_VERSION}"

  local os

  os="$(uname)"

  case "${os}" in
  Linux)
    os="linux"
    ;;
  Darwin)
    os="darwin"
    ;;
  *)
    _ die "Unknown OS type"
    ;;
  esac

  local architecture

  architecture="$(uname -m)"

  case "${architecture}" in
  x86_64)
    architecture="amd64"
    ;;
  aarch64 | arm64)
    architecture=""arm64
    ;;
  *)
    _ die "Unknown architecture: $(uname -m)"
    return 1
    ;;
  esac

  local directory="${MANAGE_REPOSITORY}/vendor/fx"

  local prefix="https://github.com/antonmedv/fx/releases/download/${version}"
  local binary="fx_${os}_${architecture}"

  if [[ ! -f "${directory}/fx" ]]; then
    mkdir -p "${directory}"

    curl -0 -S -L --progress-bar "${prefix}/${binary}" -o "${directory}/fx"
    chmod +x "${directory}/fx"

    if [[ ! -f "${HOME}/.dotfiles/bin/fd" ]]; then
      ln -s "${directory}/fx" "${HOME}/.dotfiles/bin/fx"
    fi
  fi
}
