#!/usr/bin/env bash
# @description install zoxide
# @dependency curl
# @dependency tar
# @import console/error
# @import console/die

main() {
  strict true
  verbose true

  local version="${ZOXIDE_VERSION}"

  local os

  os="$(uname)"

  case "${os}" in
  Linux)
    os="unknown-linux"
    ;;
  Darwin)
    os="apple-darwin"
    ;;
  *)
    _ die "Unknown OS type"
    ;;
  esac

  local architecture

  if [[ "${os}" == "darwin" ]]; then
    architecture="all"
  else
    architecture="$(uname -m)"

    case "${architecture}" in
    x86_64)
      architecture="x86_64"
      ;;
    aarch64 | arm64)
      architecture="aarch64"
      ;;
    *)
      _ die "Unknown architecture: $(uname -m)"
      return 1
      ;;
    esac
  fi

  local directory="${MANAGE_REPOSITORY}/vendor/zoxide"

  local prefix="https://github.com/ajeetdsouza/zoxide/releases/download/v${version}"
  local binary

  if [[ "${os}" == "apple-darwin" ]]; then
    binary="${prefix}/zoxide-v${version}-${architecture}-${os}.tar.gz"
  else
    binary="${prefix}/zoxide-v${version}-${architecture}-${os}-musl.tar.gz"
  fi

  if [[ ! -f "${directory}/zoxide" ]]; then
    mkdir -p "${directory}"

    curl -0 -S -L --progress-bar "${binary}" -o "${directory}/${binary##*/}"

    (
      cd "${directory}" || _ die
      tar -zxvf "${directory}/${binary##*/}" zoxide
      chmod +x zoxide

      if [[ ! -f "${HOME}/.dotfiles/bin/zoxide" ]]; then
        ln -s "${directory}/zoxide" "${HOME}/.dotfiles/bin/zoxide"
      fi

      rm -f "${directory}/${binary##*/}"
    )
  fi
}
