#!/usr/bin/env bash
# @description install age
# @dependency curl
# @dependency tar
# @import console/error
# @import console/die

main() {
  strict true
  verbose true

  local version="${AGE_VERSION}"

  local os

  os="$(uname)"

  case "${os}" in
  Linux)
    os="linux"
    ;;
  Darwin)
    os="darwin"
    ;;
  *)
    _ die "Unknown OS type"
    ;;
  esac

  local architecture
  architecture="$(uname -m)"

  case "${architecture}" in
  x86_64)
    architecture="amd64"
    ;;
  aarch64 | arm64)
    architecture="arm64"
    ;;
  *)
    _ die "Unknown architecture: $(uname -m)"
    return 1
    ;;
  esac

  local directory="${MANAGE_REPOSITORY}/vendor/age"

  local prefix="https://github.com/FiloSottile/age/releases/download/v${version}"
  local binary="${prefix}/age-v${version}-${os}-${architecture}.tar.gz"

  if [[ ! -f "${directory}/age" ]]; then
    mkdir -p "${directory}"

    curl -0 -S -L --progress-bar "${binary}" -o "${directory}/${binary##*/}"

    (
      cd "${directory}" || _ die
      tar -zxvf "${directory}/${binary##*/}" --strip-components=1
      chmod +x age age-keygen

      if [[ ! -f "${HOME}/.dotfiles/bin/age" ]]; then
        ln -s "${directory}/age" "${HOME}/.dotfiles/bin/age"
      fi

      if [[ ! -f "${HOME}/.dotfiles/bin/age-keygen" ]]; then
        ln -s "${directory}/age-keygen" "${HOME}/.dotfiles/bin/age-keygen"
      fi

      rm -f "${directory}/${binary##*/}" "${directory}/LICENSE"
    )
  fi
}
