#!/usr/bin/env bash
# @description clean x-dotfile
# @dependency zsh
# @dependency git
# @import dotfiles/runcoms

main () {
    verbose true
    strict true

    if [ -d "$HOME/dotfiles" ] || [ -L "$HOME/dotfiles" ]; then
        _ runcoms clean "${HOME}"/dotfiles/x/runcoms
    fi
}

